Request {
  _events: [Object: null prototype] {
    pipe: [Function],
    response: [Function],
    end: [Function],
    close: [Function],
    error: [Function]
  },
  _eventsCount: 5,
  _maxListeners: undefined,
  uri: Url {
    protocol: 'http:',
    slashes: true,
    auth: null,
    host: 'www.baidu.com',
    port: 80,
    hostname: 'www.baidu.com',
    hash: null,
    search: '?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
    query: 'pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
    pathname: '/sf/vsearch',
    path: '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
    href: 'http://www.baidu.com/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8'
  },
  method: 'HEAD',
  readable: true,
  writable: true,
  explicitMethod: true,
  _qs: Querystring {
    request: [Circular],
    lib: { formats: [Object], parse: [Function], stringify: [Function] },
    useQuerystring: undefined,
    parseOptions: {},
    stringifyOptions: {}
  },
  _auth: Auth {
    request: [Circular],
    hasAuth: false,
    sentAuth: false,
    bearerToken: null,
    user: null,
    pass: null
  },
  _oauth: OAuth { request: [Circular], params: null },
  _multipart: Multipart {
    request: [Circular],
    boundary: '033f2bfb-6bd6-4044-bcfa-0cc8b490715d',
    chunked: false,
    body: null
  },
  _redirect: Redirect {
    request: [Circular],
    followRedirect: true,
    followRedirects: true,
    followAllRedirects: false,
    followOriginalHttpMethod: false,
    allowRedirect: [Function],
    maxRedirects: 10,
    redirects: [],
    redirectsFollowed: 0,
    removeRefererHeader: false
  },
  _tunnel: Tunnel {
    request: [Circular],
    proxyHeaderWhiteList: [
                'accept',   'accept-charset',
       'accept-encoding',  'accept-language',
         'accept-ranges',    'cache-control',
      'content-encoding', 'content-language',
      'content-location',      'content-md5',
         'content-range',     'content-type',
            'connection',             'date',
                'expect',     'max-forwards',
                'pragma',          'referer',
                    'te',       'user-agent',
                   'via'
    ],
    proxyHeaderExclusiveList: []
  },
  headers: { 'content-length': 0 },
  setHeader: [Function],
  hasHeader: [Function],
  getHeader: [Function],
  removeHeader: [Function],
  localAddress: undefined,
  pool: {},
  dests: [],
  __isRequestRequest: true,
  proxy: null,
  tunnel: false,
  setHost: true,
  originalCookieHeader: undefined,
  _disableCookies: true,
  _jar: undefined,
  port: 80,
  host: 'www.baidu.com',
  path: '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
  httpModule: {
    _connectionListener: [Function: connectionListener],
    METHODS: [
             'ACL',        'BIND',
        'CHECKOUT',     'CONNECT',
            'COPY',      'DELETE',
             'GET',        'HEAD',
            'LINK',        'LOCK',
        'M-SEARCH',       'MERGE',
      'MKACTIVITY',  'MKCALENDAR',
           'MKCOL',        'MOVE',
          'NOTIFY',     'OPTIONS',
           'PATCH',        'POST',
        'PROPFIND',   'PROPPATCH',
           'PURGE',         'PUT',
          'REBIND',      'REPORT',
          'SEARCH',      'SOURCE',
       'SUBSCRIBE',       'TRACE',
          'UNBIND',      'UNLINK',
          'UNLOCK', 'UNSUBSCRIBE'
    ],
    STATUS_CODES: {
      '100': 'Continue',
      '101': 'Switching Protocols',
      '102': 'Processing',
      '103': 'Early Hints',
      '200': 'OK',
      '201': 'Created',
      '202': 'Accepted',
      '203': 'Non-Authoritative Information',
      '204': 'No Content',
      '205': 'Reset Content',
      '206': 'Partial Content',
      '207': 'Multi-Status',
      '208': 'Already Reported',
      '226': 'IM Used',
      '300': 'Multiple Choices',
      '301': 'Moved Permanently',
      '302': 'Found',
      '303': 'See Other',
      '304': 'Not Modified',
      '305': 'Use Proxy',
      '307': 'Temporary Redirect',
      '308': 'Permanent Redirect',
      '400': 'Bad Request',
      '401': 'Unauthorized',
      '402': 'Payment Required',
      '403': 'Forbidden',
      '404': 'Not Found',
      '405': 'Method Not Allowed',
      '406': 'Not Acceptable',
      '407': 'Proxy Authentication Required',
      '408': 'Request Timeout',
      '409': 'Conflict',
      '410': 'Gone',
      '411': 'Length Required',
      '412': 'Precondition Failed',
      '413': 'Payload Too Large',
      '414': 'URI Too Long',
      '415': 'Unsupported Media Type',
      '416': 'Range Not Satisfiable',
      '417': 'Expectation Failed',
      '418': "I'm a Teapot",
      '421': 'Misdirected Request',
      '422': 'Unprocessable Entity',
      '423': 'Locked',
      '424': 'Failed Dependency',
      '425': 'Unordered Collection',
      '426': 'Upgrade Required',
      '428': 'Precondition Required',
      '429': 'Too Many Requests',
      '431': 'Request Header Fields Too Large',
      '451': 'Unavailable For Legal Reasons',
      '500': 'Internal Server Error',
      '501': 'Not Implemented',
      '502': 'Bad Gateway',
      '503': 'Service Unavailable',
      '504': 'Gateway Timeout',
      '505': 'HTTP Version Not Supported',
      '506': 'Variant Also Negotiates',
      '507': 'Insufficient Storage',
      '508': 'Loop Detected',
      '509': 'Bandwidth Limit Exceeded',
      '510': 'Not Extended',
      '511': 'Network Authentication Required'
    },
    Agent: [Function: Agent] { defaultMaxSockets: Infinity },
    ClientRequest: [Function: ClientRequest],
    IncomingMessage: [Function: IncomingMessage],
    OutgoingMessage: [Function: OutgoingMessage],
    Server: [Function: Server],
    ServerResponse: [Function: ServerResponse],
    createServer: [Function: createServer],
    get: [Function: get],
    request: [Function: request],
    maxHeaderSize: [Getter],
    globalAgent: [Getter/Setter]
  },
  agentClass: [Function: Agent] { defaultMaxSockets: Infinity },
  agent: Agent {
    _events: [Object: null prototype] { free: [Function] },
    _eventsCount: 1,
    _maxListeners: undefined,
    defaultPort: 80,
    protocol: 'http:',
    options: { path: null },
    requests: {},
    sockets: {
      'www.baidu.com:80:': [Array],
      'fanyi.baidu.com:80:': [Array],
      'tieba.baidu.com:80:': [Array],
      'www.iqiyi.com:80:': [Array],
      'image.baidu.com:80:': [Array],
      'www.pc6.com:80:': [Array],
      'app.mi.com:80:': [Array]
    },
    freeSockets: {},
    keepAliveMsecs: 1000,
    keepAlive: false,
    maxSockets: Infinity,
    maxFreeSockets: 256
  },
  _started: true,
  href: 'http://www.baidu.com/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
  req: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      response: [Function: bound ],
      error: [Function: bound ],
      drain: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'HEAD ' +
      '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8 ' +
      'HTTP/1.1\r' +
      '\nhost: www.baidu.com\r' +
      '\ncontent-length: 0\r' +
      '\nConnection: close\r' +
      '\n\r' +
      '\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256
    },
    socketPath: undefined,
    method: 'HEAD',
    path: '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
    _ended: false,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: false,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      request: [Circular],
      toJSON: [Function: responseToJSON],
      caseless: [Caseless]
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: HTTPParser {
      '0': [Function: parserOnHeaders],
      '1': [Function: parserOnHeadersComplete],
      '2': [Function: parserOnBody],
      '3': [Function: parserOnMessageComplete],
      '4': null,
      _headers: [],
      _url: '',
      socket: [Socket],
      incoming: [IncomingMessage],
      outgoing: [Circular],
      maxHeaderPairs: 2000,
      _consumed: false,
      onIncoming: [Function: parserOnIncomingClient]
    },
    maxHeadersCount: null,
    [Symbol(isCorked)]: false,
    [Symbol(outHeadersKey)]: [Object: null prototype] {
      host: [Array],
      'content-length': [Array]
    }
  },
  ntick: true,
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: true,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: true,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] { end: [Array], close: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: false,
    headers: {
      bdpagetype: '3',
      bdqid: '0xec6c3d3c0008185b',
      'cache-control': 'private',
      'content-type': 'text/html;charset=utf-8',
      cxy_all: 'vsearch+d1c115a19fa34f55d5290cf5979f0f44',
      cxy_ex: '1566273565+2319676529+d41d8cd98f00b204e9800998ecf8427e',
      date: 'Tue, 20 Aug 2019 03:59:25 GMT',
      p3p: 'CP=" OTI DSP COR IVA OUR IND COM ", CP=" OTI DSP COR IVA OUR IND COM "',
      server: 'BWS/1.1',
      'set-cookie': [Array],
      vary: 'Accept-Encoding',
      'x-ua-compatible': 'IE=Edge,chrome=1',
      connection: 'close'
    },
    rawHeaders: [
      'Bdpagetype',
      '3',
      'Bdqid',
      '0xec6c3d3c0008185b',
      'Cache-Control',
      'private',
      'Content-Type',
      'text/html;charset=utf-8',
      'Cxy_all',
      'vsearch+d1c115a19fa34f55d5290cf5979f0f44',
      'Cxy_ex',
      '1566273565+2319676529+d41d8cd98f00b204e9800998ecf8427e',
      'Date',
      'Tue, 20 Aug 2019 03:59:25 GMT',
      'P3p',
      'CP=" OTI DSP COR IVA OUR IND COM "',
      'P3p',
      'CP=" OTI DSP COR IVA OUR IND COM "',
      'Server',
      'BWS/1.1',
      'Set-Cookie',
      'BAIDUID=70372056371E7F6440AA0106A325D8F3:FG=1; expires=Thu, ' +
        '31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; ' +
        'domain=.baidu.com',
      'Set-Cookie',
      'BIDUPSID=70372056371E7F6440AA0106A325D8F3; expires=Thu, ' +
        '31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; ' +
        'domain=.baidu.com',
      'Set-Cookie',
      'PSTM=1566273564; expires=Thu, 31-Dec-37 23:55:55 ' +
        'GMT; max-age=2147483647; path=/; domain=.baidu.com',
      'Set-Cookie',
      'BDRCVFR[fb3VbsUruOn]=mk3SLVN4HKm; path=/; domain=.baidu.com',
      'Set-Cookie',
      'delPer=0; path=/; domain=.baidu.com',
      'Set-Cookie',
      'BD_CK_SAM=1;path=/',
      'Set-Cookie',
      'PSINO=6; domain=.baidu.com; path=/',
      'Set-Cookie',
      'BDSVRTM=72; path=/',
      'Set-Cookie',
      'H_PS_PSSID=; path=/; domain=.baidu.com',
      'Vary',
      'Accept-Encoding',
      'X-Ua-Compatible',
      'IE=Edge,chrome=1',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 200,
    statusMessage: 'OK',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'HEAD ' +
        '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8 ' +
        'HTTP/1.1\r' +
        '\nhost: www.baidu.com\r' +
        '\ncontent-length: 0\r' +
        '\nConnection: close\r' +
        '\n\r' +
        '\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'HEAD',
      path: '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
      _ended: false,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object]
    },
    request: [Circular],
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] }
  },
  originalHost: 'www.baidu.com',
  originalHostHeaderName: 'host',
  responseContent: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: true,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: true,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] { end: [Array], close: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: false,
    headers: {
      bdpagetype: '3',
      bdqid: '0xec6c3d3c0008185b',
      'cache-control': 'private',
      'content-type': 'text/html;charset=utf-8',
      cxy_all: 'vsearch+d1c115a19fa34f55d5290cf5979f0f44',
      cxy_ex: '1566273565+2319676529+d41d8cd98f00b204e9800998ecf8427e',
      date: 'Tue, 20 Aug 2019 03:59:25 GMT',
      p3p: 'CP=" OTI DSP COR IVA OUR IND COM ", CP=" OTI DSP COR IVA OUR IND COM "',
      server: 'BWS/1.1',
      'set-cookie': [Array],
      vary: 'Accept-Encoding',
      'x-ua-compatible': 'IE=Edge,chrome=1',
      connection: 'close'
    },
    rawHeaders: [
      'Bdpagetype',
      '3',
      'Bdqid',
      '0xec6c3d3c0008185b',
      'Cache-Control',
      'private',
      'Content-Type',
      'text/html;charset=utf-8',
      'Cxy_all',
      'vsearch+d1c115a19fa34f55d5290cf5979f0f44',
      'Cxy_ex',
      '1566273565+2319676529+d41d8cd98f00b204e9800998ecf8427e',
      'Date',
      'Tue, 20 Aug 2019 03:59:25 GMT',
      'P3p',
      'CP=" OTI DSP COR IVA OUR IND COM "',
      'P3p',
      'CP=" OTI DSP COR IVA OUR IND COM "',
      'Server',
      'BWS/1.1',
      'Set-Cookie',
      'BAIDUID=70372056371E7F6440AA0106A325D8F3:FG=1; expires=Thu, ' +
        '31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; ' +
        'domain=.baidu.com',
      'Set-Cookie',
      'BIDUPSID=70372056371E7F6440AA0106A325D8F3; expires=Thu, ' +
        '31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; ' +
        'domain=.baidu.com',
      'Set-Cookie',
      'PSTM=1566273564; expires=Thu, 31-Dec-37 23:55:55 ' +
        'GMT; max-age=2147483647; path=/; domain=.baidu.com',
      'Set-Cookie',
      'BDRCVFR[fb3VbsUruOn]=mk3SLVN4HKm; path=/; domain=.baidu.com',
      'Set-Cookie',
      'delPer=0; path=/; domain=.baidu.com',
      'Set-Cookie',
      'BD_CK_SAM=1;path=/',
      'Set-Cookie',
      'PSINO=6; domain=.baidu.com; path=/',
      'Set-Cookie',
      'BDSVRTM=72; path=/',
      'Set-Cookie',
      'H_PS_PSSID=; path=/; domain=.baidu.com',
      'Vary',
      'Accept-Encoding',
      'X-Ua-Compatible',
      'IE=Edge,chrome=1',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 200,
    statusMessage: 'OK',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.baidu.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 125,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'HEAD ' +
        '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8 ' +
        'HTTP/1.1\r' +
        '\nhost: www.baidu.com\r' +
        '\ncontent-length: 0\r' +
        '\nConnection: close\r' +
        '\n\r' +
        '\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'HEAD',
      path: '/sf/vsearch?pd=video&tn=vsearch&lid=d844bb9e0001b0ea&ie=utf-8&rsv_pq=d844bb9e0001b0ea&wd=haha&rsv_spt=5&rsv_t=6db0LTxYwoTBr5CNdlfSzV8KDQp7%2BNxixGn9loyt%2BFSFCa6KGRUMDOS%2FIv0&rsv_bp=1&f=8',
      _ended: false,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object]
    },
    request: [Circular],
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] }
  }
}
